language: c
install:
- git submodule update --init --recursive
- git clone git://github.com/nanomsg/nanomsg.git
- pushd nanomsg
- sh autogen.sh
- ./configure --prefix=/usr
- make
- make install DESTDIR=$TRAVIS_BUILD_DIR/dist
- popd
compiler:
- gcc
- clang
script:
- cmake .
    -DCMAKE_INSTALL_PREFIX=/usr
    -DASTYLE=
    -DCMAKE_C_FLAGS=-I$TRAVIS_BUILD_DIR/dist/usr/include
    -DCMAKE_EXE_LINKER_FLAGS=-L$TRAVIS_BUILD_DIR/dist/usr/lib
- make
- LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/dist/usr/lib ctest -V
