server:
  config-addr: [ipc:///var/run/topologist/config.sock]
  updates-addr: [ipc:///var/run/topologist/updates.sock]

layouts:
  #example:
  #- server <- client

topologies:
  #simple: !Topology
  #  type: reqrep
  #  layout: simple
  #  port: 10010
  #  ip-addresses:
  #    server:
  #    - 10.0.0.3
