#
#  Copyright (c) 2013 Insollo Entertainment, LLC.  All rights reserved.
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"),
#  to deal in the Software without restriction, including without limitation
#  the rights to use, copy, modify, merge, publish, distribute, sublicense,
#  and/or sell copies of the Software, and to permit persons to whom
#  the Software is furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included
#  in all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
#  IN THE SOFTWARE.
#
__meta__:
  program-name: topologist
  default-config: /etc/topologist.yaml
  description: A configuration service implementation
    for nanoconfig and nanomsg

__types__:

  nanomsg_addr: !TagScalar
    tags:
      Bind: 0
      Connect: 1
    default-tag: Bind
    type: !String

  topology_type: !Enum
    options:
      reqrep: 1
      pipeline: 2
      pubsub: 3
      pair: 4
      bus: 5
      survey: 6

  intern: !Struct
    type: !Type topology_type
    layout: !String
    port: !Int
      min: 1
      max: 65535
      description: Default port used for the topology, if not overriden by
        per-role, or per-connection basis.
    ip-addresses: !Mapping
      description: List of ip addresses for the roles that bind on IP
      key-element: !String
      value-element: !Array
        element: !String

  extern: !Struct
    topology: !String
      description: Topology where extract the slot from
    slot: !String
      description: The name of the slot in the topology

  topology: !Choice
    choices:
      Extern: !Type extern
      Topology: !Type intern



server:

  config-addr: !Array
    element: !Type nanomsg_addr
    description: List of addresses to bind using REP socket for
      name requests

  updates-addr: !Array
    element: !Type nanomsg_addr
    description: List of addresses to bind using PUB socket for sending
      configuration updates


layouts: !Mapping
  key-element: !String
  value-element: !Array
    element: !String

topologies: !Mapping
  key-element: !String
  value-element: !Type topology


__if__:defined COMMAND_LINE:
  query_file: !String
    only-command-line: true
    command-line:
      names: [-Q, --query-file]
      metavar: FILE
    description: Text file with list of queries
  query: !String
    only-command-line: true
    command-line:
      names: [-q, --query]
      metavar: STRING
    description: Executed a query and print results
  graph: !String
    only-command-line: true
    command-line:
      names: [-G, --graph-for-topology]
      metavar: TOPOLOGY
    description: Prints dot-formatted graph for the topology
  output: !String
    only-command-line: true
    command-line:
      names: [-o, --output]
      metavar: FILE
    description: File name to write query results to
    default: "-"
